'use client';
import {useEffect,useState} from 'react';
import {ChevronDown,CircleDollarSign,Clock3,Droplets,Leaf,Menu,Search,Settings2,Star,WalletCards,X} from 'lucide-react';
type Market={symbol:string;name:string;unit:string;m:number;cap:number;status:string;expiry:string;description:string;reference:number};
type Level={price:number;size:number;total:number}; type Book={bids:Level[];asks:Level[];last:number};
type Account={cash:number;reserved_cash:number;available_cash:number;open_orders:number;positions:Record<string,{available:number;reserved:number}>};
const API=process.env.NEXT_PUBLIC_ENGINE_URL||'http://localhost:8080'; const WALLET='demo-user';
const markets:Market[]=[
 {symbol:'MILK',name:'US Class III Milk',unit:'USD/cwt',m:2000,cap:25,status:'LIVE DEMO',expiry:'Oct 2026',description:'USDA announced Class III price · 2,000 cwt / 200,000 lb exposure',reference:16.64},
 {symbol:'POTATO',name:'US Russet Potato Index v1',unit:'USD / 50 lb carton',m:1,cap:35,status:'HISTORICAL / DEMO',expiry:'Oct 2026',description:'Russet Norkotah · U.S. One · 70-count · 50 lb cartons',reference:20},
 {symbol:'TOMATO',name:'US Round Tomato Index v1',unit:'USD / 25 lb carton',m:1,cap:40,status:'HISTORICAL / DEMO',expiry:'Oct 2026',description:'Round mature-green · U.S. One or better · 5x6 · 25 lb cartons',reference:18},
 {symbol:'WHEAT',name:'US Wheat Index v1',unit:'USD / bushel',m:1,cap:15,status:'HISTORICAL / DEMO',expiry:'Oct 2026',description:'US domestic cash benchmark · audit gate before issuance',reference:6.1},
 {symbol:'CORN',name:'US Corn Index v1',unit:'USD / bushel',m:1,cap:10,status:'HISTORICAL / DEMO',expiry:'Oct 2026',description:'US domestic cash benchmark · audit gate before issuance',reference:4.5},
 {symbol:'RICE',name:'US Rice Index v1',unit:'USD / cwt',m:1,cap:30,status:'HISTORICAL / DEMO',expiry:'Oct 2026',description:'US long-grain benchmark · audit gate before issuance',reference:18},
 {symbol:'SOYBEAN',name:'US Soybean Index v1',unit:'USD / bushel',m:1,cap:25,status:'HISTORICAL / DEMO',expiry:'Oct 2026',description:'US domestic cash benchmark · audit gate before issuance',reference:10.2},
 {symbol:'DRY_BEAN',name:'US Dry Bean Index v1',unit:'USD / cwt',m:1,cap:80,status:'HISTORICAL / DEMO',expiry:'Oct 2026',description:'US dry edible bean benchmark · audit gate before issuance',reference:42}
];
const emptyAccount:Account={cash:0,reserved_cash:0,available_cash:0,open_orders:0,positions:{}};
export default function Home(){
 const [market,setMarket]=useState(markets[0]); const claim='SPOT'; const [book,setBook]=useState<Book>({bids:[],asks:[],last:0}); const [account,setAccount]=useState<Account>(emptyAccount); const [connected,setConnected]=useState(false); const [ticket,setTicket]=useState<'Market'|'Limit'>('Limit'); const [buy,setBuy]=useState(true); const [price,setPrice]=useState('16.72'); const [qty,setQty]=useState('1'); const [notice,setNotice]=useState(''); const [mobileMenu,setMobileMenu]=useState(false);
 const mark=book.last||market.reference; const orderValue=(+price||0)*(+qty||0); const position=account.positions[`${market.symbol}:SPOT`]?.available||0;
 useEffect(()=>{fetch(`${API}/api/book/${market.symbol}/${claim}`).then(r=>r.json()).then((b:Book)=>{setBook(b);if(b.asks[0])setPrice(b.asks[0].price.toFixed(2))}).catch(()=>setNotice('Start the Rust engine on port 8080.'))},[market.symbol,claim]);
 useEffect(()=>{if(connected)fetch(`${API}/api/account/${WALLET}`).then(r=>r.json()).then(setAccount)},[connected,book]);
 const connect=async()=>{const r=await fetch(`${API}/api/fund`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({wallet:WALLET,amount:10000})});if(r.ok){setConnected(true);setNotice('Demo collateral funded.')}};
 const submit=async()=>{if(!connected){await connect();return}const r=await fetch(`${API}/api/orders`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({wallet:WALLET,symbol:market.symbol,claim,side:buy?'buy':'sell',price:+price,qty:+qty,client_id:`ui-${Date.now()}`})});const d=await r.json();if(!r.ok)setNotice(typeof d==='string'?d:'Order rejected');else{setNotice(d.some((x:any)=>x.status==='filled/cancelled')?'Filled against demo maker':'Order resting in book');setBook(await fetch(`${API}/api/book/${market.symbol}/${claim}`).then(x=>x.json()))}};
 const selectMarket=(m:Market)=>{setMarket(m);setNotice('');setMobileMenu(false)};
 return <main className="hl-app">
  <header className="hl-nav"><button className="icon-btn mobile-only" onClick={()=>setMobileMenu(!mobileMenu)}><Menu size={18}/></button><div className="hl-logo"><span className="hl-logo-mark">◒</span><span>Raw<span>Market</span></span></div><nav><button className="nav-active">Trade</button><button>Portfolio</button><button>Markets</button><button>Settlement</button><button>More <ChevronDown size={13}/></button></nav><div className="nav-right"><button className="icon-btn"><Search size={16}/></button><button className="icon-btn"><Settings2 size={16}/></button><button className="connect" onClick={connect}><WalletCards size={15}/>{connected?'demo-user':'Connect'}</button></div></header>
  {mobileMenu&&<div className="market-drawer"><div className="drawer-head"><b>Markets</b><button onClick={()=>setMobileMenu(false)}><X size={16}/></button></div>{markets.map(m=><button key={m.symbol} onClick={()=>selectMarket(m)} className={market.symbol===m.symbol?'chosen':''}><span>{m.symbol}</span><small>{m.unit}</small><em>{m.status==='LIVE DEMO'?'●':'◌'}</em></button>)}</div>}
  <section className="asset-strip"><button className="asset-select" onClick={()=>setMobileMenu(!mobileMenu)}><span className="asset-icon">{market.symbol==='MILK'?<Droplets size={16}/>:<Leaf size={16}/>}</span><strong>{market.symbol}-USD</strong><ChevronDown size={15}/></button><span className="asset-status">{market.status==='LIVE DEMO'?'●':'◌'} {market.status.toLowerCase()}</span><div className="asset-metrics"><div><small>REFERENCE</small><b>${market.reference.toFixed(2)}</b></div><div><small>MARK</small><b>${mark.toFixed(2)}</b></div><div><small>UNIT</small><b>{market.unit.replace('USD/','')}</b></div><div><small>EXPIRY</small><b>{market.expiry}</b></div><div><small>MODE</small><b className="amber">Spot</b></div></div><button className="star"><Star size={15}/></button></section>
  <section className="terminal-grid">
   <div className="chart-pane"><div className="chart-tabs"><button className="active">Chart</button><button>Methodology</button></div><div className="chart-toolbar"><button>5m</button><button className="active">1h</button><button>1D</button><ChevronDown size={13}/><span className="tool-divider"/><button>▥</button><button>ƒx Indicators</button><span className="toolbar-spacer"/><button>⛶</button></div><div className="tv-chart"><div className="chart-y"><span>${(mark+2).toFixed(2)}</span><span>${(mark+1).toFixed(2)}</span><span>${mark.toFixed(2)}</span><span>${(mark-1).toFixed(2)}</span><span>${(mark-2).toFixed(2)}</span></div><svg viewBox="0 0 900 500" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#56d9a0" stopOpacity=".20"/><stop offset="1" stopColor="#56d9a0" stopOpacity="0"/></linearGradient></defs><g className="grid-lines"><path d="M0 50H900M0 140H900M0 230H900M0 320H900M0 410H900"/><path d="M100 0V500M250 0V500M400 0V500M550 0V500M700 0V500M850 0V500"/></g><path d="M0 300 C40 280 65 340 105 280 S160 315 205 230 S260 260 300 210 S360 250 405 165 S460 210 500 145 S545 190 590 220 S640 180 690 130 S750 170 800 110 S850 145 900 75 L900 500 L0 500Z" fill="url(#area)"/><path d="M0 300 C40 280 65 340 105 280 S160 315 205 230 S260 260 300 210 S360 250 405 165 S460 210 500 145 S545 190 590 220 S640 180 690 130 S750 170 800 110 S850 145 900 75" fill="none" stroke="#57d99f" strokeWidth="2.5"/><path d="M0 205H900" stroke="#8b96a3" strokeDasharray="6 7" opacity=".65"/><circle cx="900" cy="75" r="4" fill="#57d99f"/><rect x="838" y="58" rx="3" width="62" height="22" fill="#57d99f"/><text x="847" y="73" fill="#06130d" fontSize="11">{mark.toFixed(2)}</text><g className="volume"><rect x="40" y="430" width="18" height="40"/><rect x="75" y="400" width="18" height="70"/><rect x="110" y="445" width="18" height="25"/><rect x="145" y="390" width="18" height="80"/><rect x="180" y="420" width="18" height="50"/><rect x="215" y="450" width="18" height="20"/><rect x="250" y="405" width="18" height="65"/><rect x="285" y="435" width="18" height="35"/><rect x="320" y="415" width="18" height="55"/><rect x="355" y="445" width="18" height="25"/></g></svg><div className="chart-y bottom"><span>Sep 08</span><span>Sep 10</span><span>Sep 12</span><span>Sep 13</span></div><div className="chart-label">{market.symbol}-USD · 1h · RawMarket <span>●</span></div></div></div>
   <aside className="right-rail"><div className="rail-tabs"><button className="active">Order Book</button><button>Trades</button><button>⋮</button></div><div className="book-controls"><span>0.01</span><ChevronDown size={12}/><span className="book-asset">{market.symbol}<ChevronDown size={12}/></span></div><div className="book-head"><span>Price</span><span>Size (spot)</span><span>Total</span></div><div className="book-levels">{book.asks.map((l,i)=><div className="level ask" key={'a'+i}><span>{l.price.toFixed(2)}</span><span>{l.size}</span><span>{l.total.toFixed(2)}</span></div>)}<div className="book-spread"><span>Spread</span><b>{book.asks[0]&&book.bids[0]?(book.asks[0].price-book.bids[0].price).toFixed(2):'—'}</b><small>{book.asks[0]&&book.bids[0]?((book.asks[0].price-book.bids[0].price)/mark*100).toFixed(3)+'%':''}</small></div>{book.bids.map((l,i)=><div className="level bid" key={'b'+i}><span>{l.price.toFixed(2)}</span><span>{l.size}</span><span>{l.total.toFixed(2)}</span></div>)}</div><div className="ticket"><div className="ticket-top"><button className="ticket-mode">Spot trading <ChevronDown size={13}/></button><button className="ticket-mode">USD</button></div><div className="ticket-types"><button className={ticket==='Market'?'active':''} onClick={()=>setTicket('Market')}>Market</button><button className={ticket==='Limit'?'active':''} onClick={()=>setTicket('Limit')}>Limit</button></div><div className="ticket-side"><button className={buy?'active buy':''} onClick={()=>setBuy(true)}>Buy</button><button className={!buy?'active sell':''} onClick={()=>setBuy(false)}>Sell</button></div><div className="available"><span>Available cash</span><b>${account.available_cash.toFixed(2)} USD</b></div><div className="available"><span>Current spot position</span><b>{position} {market.symbol}</b></div><label>Price <span>{market.unit}</span></label><div className="ticket-input"><input value={price} onChange={e=>setPrice(e.target.value)} disabled={ticket==='Market'}/><span>USD</span></div><label>Size <span>units</span></label><div className="ticket-input"><input value={qty} onChange={e=>setQty(e.target.value)}/><span>{market.symbol}</span></div><button className={'place '+(!buy?'red':'')} onClick={submit}><CircleDollarSign size={16}/>{connected?'Place order':'Fund demo wallet'}</button>{notice&&<div className="ticket-notice">{notice}</div>}<div className="ticket-summary"><div><span>Order value</span><b>${orderValue.toFixed(2)} USD</b></div><div><span>Trading mode</span><b>Spot · 1x</b></div></div></div></aside>
  </section>
  <section className="account-dock"><div className="dock-tabs"><button className="active">Balances ({connected?'1':'0'})</button><button>Spot Positions</button><button>Open Orders ({account.open_orders})</button><button>Fills</button><button>Settlement History</button><span/><button><ChevronDown size={13}/> {market.symbol}</button></div><div className="dock-body"><div className="balance-card"><span>Portfolio value</span><strong>${account.cash.toLocaleString(undefined,{minimumFractionDigits:2})}</strong></div><div className="balance-card"><span>Available cash</span><strong>${account.available_cash.toFixed(2)}</strong></div><div className="balance-card"><span>Reserved cash</span><strong>${account.reserved_cash.toFixed(2)}</strong></div><div className="balance-card"><span>Spot inventory</span><strong>{position} {market.symbol}</strong></div><div className="dock-note"><Clock3 size={14}/> Spot only · no leverage · no shorting</div></div></section>
  <footer className="hl-footer"><span><i/> Online</span><span>RawMarket v0.1.0</span><span>USDA evidence pinned · ATS deployment pending</span></footer>
 </main>
}
