import {Activity,BookOpen} from 'lucide-react';
import {money,stamp} from '@/lib/format';
import type {Account,DockTab,Order,Position,Trade} from '@/lib/types';

export function PortfolioDock({tab,onTab,account,openOrders,fills,wallet,symbol,position,onCancel}:{tab:DockTab;onTab:(tab:DockTab)=>void;account:Account;openOrders:Order[];fills:Trade[];wallet:string;symbol:string;position:Position;onCancel:(id:string)=>void}){
  return <section className="portfolio panel">
    <div className="portfolio-tabs"><button className={tab==='orders'?'selected':''} onClick={()=>onTab('orders')}>Open orders <b>{openOrders.length}</b></button><button className={tab==='fills'?'selected':''} onClick={()=>onTab('fills')}>Trade history <b>{fills.length}</b></button><button className={tab==='balances'?'selected':''} onClick={()=>onTab('balances')}>Balances</button><div className="portfolio-value"><span>PORTFOLIO</span><strong>{money(account.cash)}</strong><small>{money(account.reserved_cash)} reserved</small></div></div>
    {tab==='orders'&&<div className="data-table"><div className="table-head"><span>Market</span><span>Side</span><span>Type</span><span>Price</span><span>Filled / Qty</span><span>Status</span><span/></div>{openOrders.length?openOrders.map(order=><div className="table-row" key={order.id}><strong>{order.symbol}/USD</strong><span className={order.side==='buy'?'positive':'negative'}>{order.side.toUpperCase()}</span><span>{order.order_type}</span><span>{money(order.price)}</span><span>{order.filled} / {order.qty}</span><span><i className="open-dot"/> {order.status}</span><button onClick={()=>onCancel(order.id)}>Cancel</button></div>):<div className="table-empty"><BookOpen size={19}/><div><strong>No open orders</strong><span>Your active orders will appear here.</span></div></div>}</div>}
    {tab==='fills'&&<div className="data-table"><div className="table-head six"><span>Market</span><span>Side</span><span>Price</span><span>Quantity</span><span>Value</span><span>Time</span></div>{fills.length?fills.map(fill=>{const mine=fill.buyer===wallet?'buy':'sell';return <div className="table-row six" key={fill.id}><strong>{fill.symbol}/USD</strong><span className={mine==='buy'?'positive':'negative'}>{mine.toUpperCase()}</span><span>{money(fill.price)}</span><span>{fill.qty}</span><span>{money(fill.price*fill.qty)}</span><span>{stamp(fill.timestamp)}</span></div>}):<div className="table-empty"><Activity size={19}/><div><strong>No trades yet</strong><span>Your completed trades will appear here.</span></div></div>}</div>}
    {tab==='balances'&&<div className="balance-grid"><div><span>Cash balance</span><strong>{money(account.cash)}</strong><small>USD</small></div><div><span>Available cash</span><strong>{money(account.available_cash)}</strong><small>After reservations</small></div><div><span>Reserved cash</span><strong>{money(account.reserved_cash)}</strong><small>Open buy orders</small></div><div><span>{symbol} inventory</span><strong>{position.available}</strong><small>{position.reserved} reserved</small></div></div>}
  </section>;
}
